# Generated by Django 3.2.5 on 2021-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=20)),
            ],
        ),
    ]
