# Generated by Django 3.2.5 on 2021-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0002_alter_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('is_admin_user', models.BooleanField(verbose_name='Admin Checked')),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=6)),
                ('dob', models.DateField()),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
