# Generated by Django 3.2.5 on 2021-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0003_userform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userform',
            name='is_admin_user',
            field=models.BooleanField(verbose_name='is_admin_user'),
        ),
    ]
