# Generated by Django 3.2.5 on 2021-08-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0004_auto_20210812_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='is_admin_user',
        ),
    ]
