# Generated by Django 3.2.5 on 2021-08-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0007_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
