# Generated by Django 3.2.5 on 2021-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager_name',
            field=models.CharField(choices=[('Rakesh', 'Rakesh'), ('Yasin', 'Yasin'), ('Jaya', 'Jaya'), ('Kannan', 'Kannan')], max_length=50),
        ),
    ]
