# Generated by Django 3.2.5 on 2021-08-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_employee',
        ),
    ]
