# Generated by Django 3.2.5 on 2021-08-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_app', '0003_auto_20210821_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_reason', models.CharField(help_text='What is the reason for your leave?', max_length=100)),
                ('leave_type', models.CharField(choices=[('personal leave', 'Personal Leave'), ('carry forward', 'Carry Forward'), ('compensatory leave', 'Compensatory Leave')], max_length=20)),
                ('cancel_leave', models.CharField(help_text='What is the reason for cancelling leave?', max_length=100)),
                ('manager_name', models.CharField(help_text='Requesting to', max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
