# Generated by Django 3.2.5 on 2021-08-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_auto_20210823_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='requested', max_length=20),
        ),
    ]
