# Generated by Django 3.2.5 on 2021-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='cancel_leave',
            field=models.CharField(default='None', help_text='What is the reason for cancelling leave?', max_length=100),
        ),
    ]
