# Generated by Django 3.2.5 on 2021-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0007_alter_leaverequest_cancel_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='no_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
