# Generated by Django 3.2.5 on 2021-08-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_alter_leaveapprove_manager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprove',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='leaveapprove',
            name='manager_name',
        ),
    ]
