# Generated by Django 3.2.5 on 2021-08-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_leaveapprove_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapprove',
            name='manager_name',
            field=models.CharField(max_length=20),
        ),
    ]
