# Generated by Django 3.2.5 on 2021-08-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0012_alter_leaveapprove_manager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprove',
            name='manager_name',
        ),
    ]
