# Generated by Django 3.2.5 on 2021-08-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0013_remove_leaveapprove_manager_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='manager_name',
        ),
    ]
