# Generated by Django 3.2.5 on 2021-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0014_remove_leaverequest_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapprove',
            name='manager_name',
            field=models.CharField(default='Yasin', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_name',
            field=models.CharField(default='Yasin', max_length=50),
        ),
    ]
