# Generated by Django 3.2.5 on 2021-09-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0006_leaveapprove_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapprove',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='requested', max_length=100),
        ),
    ]
