# Generated by Django 3.2.5 on 2021-09-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0007_auto_20210901_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
