# Generated by Django 3.2.5 on 2021-09-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(),
        ),
    ]
