# Generated by Django 3.2.5 on 2021-09-02 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0009_auto_20210902_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(default=datetime.date(2021, 9, 2)),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(default=datetime.date(2021, 9, 2)),
        ),
    ]
