# Generated by Django 3.2.5 on 2021-09-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0014_auto_20210902_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='cancel_leave',
            new_name='cancel_reason',
        ),
    ]
