# Generated by Django 3.2.5 on 2021-09-06 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0016_auto_20210903_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
