# Generated by Django 3.2.5 on 2021-09-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0019_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApprove',
        ),
    ]
