# Generated by Django 3.2.5 on 2021-08-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0003_rename_emp_name_leaveapprove_emp_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapprove',
            name='emp_name_id',
        ),
        migrations.AddField(
            model_name='leaveapprove',
            name='emp_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LeaveApp.leaverequest'),
        ),
    ]
