# Generated by Django 3.2.5 on 2021-09-02 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0010_auto_20210902_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
