# Generated by Django 3.2.5 on 2021-09-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0015_rename_cancel_leave_leaverequest_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateTimeField(default='2021-09-15'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateTimeField(default='2021-09-30'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager_name',
            field=models.CharField(choices=[('Yasin', 'Yasin'), ('Rakesh', 'Rakesh'), ('Jaya', 'Jaya')], max_length=50),
        ),
    ]
