# Generated by Django 3.2.5 on 2021-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveApp', '0018_alter_leaverequest_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Personal leave', 'Personal Leave'), ('Carry forward', 'Carry Forward'), ('Compensatory leave', 'Compensatory Leave')], max_length=20),
        ),
    ]
