# Generated by Django 3.2.5 on 2021-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaction',
            name='empname',
            field=models.CharField(default='Individual', max_length=50),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='leave_reason',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='leave_type',
            field=models.CharField(choices=[('personal leave', 'Personal Leave'), ('carry forward', 'Carry Forward'), ('compensatory leave', 'Compensatory Leave')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeaction',
            name='request',
            field=models.CharField(default='Individual', max_length=50),
        ),
    ]
