# Generated by Django 3.2.5 on 2021-08-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0005_remove_userform_is_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
