list = ['C', 'HTML', 'CSS', 'Java', 'Python']
print(list)
list.append('MySql')
print(list)
list.insert(1,'C++')
print(list)
a=list.count('Python')
print(a)
list.sort()
print(list)
a = list.copy()
print(a)
list.reverse()
print(list)
l = len(list)
print(l)
list.pop()
print(list)
l = len(list)
print(l)
list.remove('CSS')
print(list)
print(len(list))
list.insert(0, 'XML')
print(list)
list.extend(a)
print(list)
a.clear()
print(a, len(a))

