t = ('orange', 'apple', 'grapes', 'banana',  'orbnge')
print(t)
l = len(t)
print(l)
ma = max(t)
print(ma)
mi = min(t)
print(mi)
num = (3,10,54,22,65)
s = sum(num)
print(s)
a = any((0,0))
print(a)
a = any((0, 23, 'Kamali'))
print(a)
b = all(t)
print(b)
b = all((0, 23, 'Kamali'))
print(b)
sort = sorted(t)
print(sort)
t1 = ('orange', 'apple', 'grapes', 'banana', 'apple',  'orbnge')
c = t1.count('apple')
#print cmp(t,t1)
print(c)
i = t1.index('apple')
print(i)
com = t.cmp(t1)
print(com)