# Generated by Django 3.2.5 on 2021-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_name',
            field=models.CharField(choices=[('Rakesh', 'Rakesh'), ('Yasin', 'Yasin'), ('Jaya', 'Jaya')], default='Rakesh', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='qwerty@123', max_length=10),
        ),
    ]
