# Generated by Django 3.2.5 on 2021-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210903_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='domain',
            field=models.CharField(default='Pyhton', max_length=30),
        ),
    ]
