# Generated by Django 3.2.5 on 2021-09-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210907_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager_name',
            field=models.CharField(choices=[('Rakesh', 'Rakesh'), ('Yasin', 'Yasin'), ('Jaya', 'Jaya')], default='None', max_length=50),
        ),
    ]
