# Generated by Django 3.2.5 on 2021-09-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='leave_days',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=20),
        ),
    ]
