# Generated by Django 3.2.5 on 2021-09-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userprofile_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='domain',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
